providers = ["node"]

[phases.install]
cmds = ["npm ci --prefix backend"]

[phases.build]
cmds = ["npx prisma generate --prefix backend", "npm run build --prefix backend", "npx prisma db push --prefix backend"]

[start]
cmd = "npm start --prefix backend"
