providers = ["node"]

[phases.install]
cmds = ["npm ci --prefix backend"]

[phases.build]
cmds = ["npm run build --prefix backend", "npx prisma migrate", "npx prisma db push"]

[start]
cmd = "npm start --prefix backend"
