providers = ["node"]

[phases.install]
cmds = ["npm ci --prefix backend"]

[phases.build]
cmds = ["cd backend && npx prisma generate", "npm run build --prefix backend", "cd backend && npx prisma db push --prefix backend"]

[start]
cmd = "npm start --prefix backend"
