targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/**
      freezed:
        generate_for:
          - lib/**
      json_serializable:
        generate_for:
          - lib/**
      retrofit_generator:
        generate_for:
          - lib/**
      drift_dev:
        generate_for:
          - lib/**
